const hairList = {
    0: [
        { id: 0, name: "Close Shave", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz" },
        { id: 1, name: "Buzzcut", collection: "multiplayer_overlays", overlay: "NG_M_Hair_001" },
        { id: 2, name: "Faux Hawk", collection: "multiplayer_overlays", overlay: "NG_M_Hair_002" },
        { id: 3, name: "Hipster", collection: "multiplayer_overlays", overlay: "NG_M_Hair_003" },
        { id: 4, name: "Side Parting", collection: "multiplayer_overlays", overlay: "NG_M_Hair_004" },
        { id: 5, name: "Shorter Cut", collection: "multiplayer_overlays", overlay: "NG_M_Hair_005" },
        { id: 6, name: "Biker", collection: "multiplayer_overlays", overlay: "NG_M_Hair_006" },
        { id: 7, name: "Ponytail", collection: "multiplayer_overlays", overlay: "NG_M_Hair_007" },
        { id: 8, name: "Cornrows", collection: "multiplayer_overlays", overlay: "NG_M_Hair_008" },
        { id: 9, name: "Slicked", collection: "multiplayer_overlays", overlay: "NG_M_Hair_009" },
        { id: 10, name: "Short Brushed", collection: "multiplayer_overlays", overlay: "NG_M_Hair_013" },
        { id: 11, name: "Spikey", collection: "multiplayer_overlays", overlay: "NG_M_Hair_002" },
        { id: 12, name: "Caesar", collection: "multiplayer_overlays", overlay: "NG_M_Hair_011" },
        { id: 13, name: "Chopped", collection: "multiplayer_overlays", overlay: "NG_M_Hair_012" },
        { id: 14, name: "Dreads", collection: "multiplayer_overlays", overlay: "NG_M_Hair_014" },
        { id: 15, name: "Long Hair", collection: "multiplayer_overlays", overlay: "NG_M_Hair_015" },
        { id: 16, name: "Shaggy Curls", collection: "multiplayer_overlays", overlay: "NGBea_M_Hair_000" },
        { id: 17, name: "Surfer Dude", collection: "multiplayer_overlays", overlay: "NGBea_M_Hair_001" },
        { id: 18, name: "Short Side Part", collection: "multiplayer_overlays", overlay: "NGBus_M_Hair_000" },
        { id: 19, name: "High Slicked Sides", collection: "multiplayer_overlays", overlay: "NGBus_M_Hair_001" },
        { id: 20, name: "Long Slicked", collection: "multiplayer_overlays", overlay: "NGHip_M_Hair_000" },
        { id: 21, name: "Hipster Youth", collection: "multiplayer_overlays", overlay: "NGHip_M_Hair_001" },
        { id: 22, name: "Mullet", collection: "multiplayer_overlays", overlay: "NGInd_M_Hair_000" },
        { id: 24, name: "Classic Cornrows", collection: "mplowrider_overlays", overlay: "LR_M_Hair_000" },
        { id: 25, name: "Palm Cornrows", collection: "mplowrider_overlays", overlay: "LR_M_Hair_001" },
        { id: 26, name: "Lightning Cornrows", collection: "mplowrider_overlays", overlay: "LR_M_Hair_002" },
        { id: 27, name: "Whipped Cornrows", collection: "mplowrider_overlays", overlay: "LR_M_Hair_003" },
        { id: 28, name: "Zig Zag Cornrows", collection: "mplowrider2_overlays", overlay: "LR_M_Hair_004" },
        { id: 29, name: "Snail Cornrows", collection: "mplowrider2_overlays", overlay: "LR_M_Hair_005" },
        { id: 30, name: "Hightop", collection: "mplowrider2_overlays", overlay: "LR_M_Hair_006" },
        { id: 31, name: "Loose Swept Back", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_000_M" },
        { id: 32, name: "Undercut Swept Back", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_001_M" },
        { id: 33, name: "Undercut Swept Side", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_002_M" },
        { id: 34, name: "Spiked Mohawk", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_003_M" },
        { id: 35, name: "Mod", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_004_M" },
        { id: 36, name: "Layered Mod", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_005_M" },
        { id: 72, name: "Flattop", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_M_000_M" },
        { id: 73, name: "Military Buzzcut", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_M_001_M" }
    ],
    1:     // female leng 40
        [
            { id: 0, name: "Close Shave", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz" },
            { id: 1, name: "Short", collection: "multiplayer_overlays", overlay: "NG_F_Hair_001" },
            { id: 2, name: "Layered Bob", collection: "multiplayer_overlays", overlay: "NG_F_Hair_002" },
            { id: 3, name: "Pigtails", collection: "multiplayer_overlays", overlay: "NG_F_Hair_003" },
            { id: 4, name: "Ponytail", collection: "multiplayer_overlays", overlay: "NG_F_Hair_004" },
            { id: 5, name: "Braided Mohawk", collection: "multiplayer_overlays", overlay: "NG_F_Hair_005" },
            { id: 6, name: "Braids", collection: "multiplayer_overlays", overlay: "NG_F_Hair_006" },
            { id: 7, name: "Bob", collection: "multiplayer_overlays", overlay: "NG_F_Hair_007" },
            { id: 8, name: "Faux Hawk", collection: "multiplayer_overlays", overlay: "NG_F_Hair_008" },
            { id: 9, name: "French Twist", collection: "multiplayer_overlays", overlay: "NG_F_Hair_009" },
            { id: 10, name: "Long Bob", collection: "multiplayer_overlays", overlay: "NG_F_Hair_010" },
            { id: 11, name: "Loose Tied", collection: "multiplayer_overlays", overlay: "NG_F_Hair_011" },
            { id: 12, name: "Pixie", collection: "multiplayer_overlays", overlay: "NG_F_Hair_012" },
            { id: 13, name: "Shaved Bangs", collection: "multiplayer_overlays", overlay: "NG_F_Hair_013" },
            { id: 14, name: "Top Knot", collection: "multiplayer_overlays", overlay: "NG_M_Hair_014" },
            { id: 15, name: "Wavy Bob", collection: "multiplayer_overlays", overlay: "NG_M_Hair_015" },
            { id: 16, name: "Messy Bun", collection: "multiplayer_overlays", overlay: "NGBea_F_Hair_000" },
            { id: 17, name: "Pin Up Girl", collection: "multiplayer_overlays", overlay: "NGBea_F_Hair_001" },
            { id: 18, name: "Tight Bun", collection: "multiplayer_overlays", overlay: "NG_F_Hair_007" },
            { id: 19, name: "Twisted Bob", collection: "multiplayer_overlays", overlay: "NGBus_F_Hair_000" },
            { id: 20, name: "Flapper Bob", collection: "multiplayer_overlays", overlay: "NGBus_F_Hair_001" },
            { id: 21, name: "Big Bangs", collection: "multiplayer_overlays", overlay: "NGBea_F_Hair_001" },
            { id: 22, name: "Braided Top Knot", collection: "multiplayer_overlays", overlay: "NGHip_F_Hair_000" },
            { id: 23, name: "Mullet", collection: "multiplayer_overlays", overlay: "NGInd_F_Hair_000" },
            { id: 25, name: "Pinched Cornrows", collection: "mplowrider_overlays", overlay: "LR_F_Hair_000" },
            { id: 26, name: "Leaf Cornrows", collection: "mplowrider_overlays", overlay: "LR_F_Hair_001" },
            { id: 27, name: "Zig Zag Cornrows", collection: "mplowrider_overlays", overlay: "LR_F_Hair_002" },
            { id: 28, name: "Pigtail Bangs", collection: "mplowrider2_overlays", overlay: "LR_F_Hair_003" },
            { id: 29, name: "Wave Braids", collection: "mplowrider2_overlays", overlay: "LR_F_Hair_003" },
            { id: 30, name: "Coil Braids", collection: "mplowrider2_overlays", overlay: "LR_F_Hair_004" },
            { id: 31, name: "Rolled Quiff", collection: "mplowrider2_overlays", overlay: "LR_F_Hair_006" },
            { id: 32, name: "Loose Swept Back", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_000_F" },
            { id: 33, name: "Undercut Swept Back", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_001_F" },
            { id: 34, name: "Undercut Swept Side", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_002_F" },
            { id: 35, name: "Spiked Mohawk", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_003_F" },
            { id: 36, name: "Bandana and Braid", collection: "multiplayer_overlays", overlay: "NG_F_Hair_003" },
            { id: 37, name: "Layered Mod", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_006_F" },
            { id: 38, name: "Skinbyrd", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_004_F" },
            { id: 76, name: "Neat Bun", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_F_000_F" },
            { id: 77, name: "Short Bob", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_F_001_F" }
        ]
}

const facialHairList = ["Нет", "Легкая щетина", "Бальбоа", "Круглая борода", "Эспаньолка",
    "Козлиная бородка", "Островок", "Тонкая бородка", "Неряха", "Мушкетер", "Усы", "Ухоженная борода",
    "Щетина", "Тонкая бородка", "Подкова", "Карандаш", "Ремень", "Бальбо и баки", "Баки", "Неряшливая борода",
    "Дали", "Дали и борода", "Руль", "Фауст", "Англичанин", "Голливуд", "Фу Манчу", "Островок с баками", "Широкие баки", "Ширма"];

const hairColorList = [
    "#211f1c", "#55362f", "#4b382e", "#4d291b", 
    "#70351e", "#904422", "#a55c36", "#a56944", 
    "#ac744f", "#ae7d57", "#be9161", "#cda670", 
    "#c8a370", "#d5a861", "#e0b775", "#e8c487", 
    "#b78457", "#a85d3d", "#963523", "#7c1411", 
    "#921812", "#a81c14", "#cb371e", "#de411b", 
    "#be532f", "#d34d21", "#907867", "#a78e7a", 
    "#d4bda9", "#e4cfbe"
];

exports = {
    hairList: hairList,
    facialHairList: facialHairList,
    hairColorList: hairColorList
}